---
abstract: 'Use Cached Responses of Certain URIs'
author:
  - 'Ingy döt Net <ingy@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Plack::Middleware::Cache
name: Plack-Middleware-Cache
no_index:
  directory:
    - inc
    - t
requires:
  Digest::MD5: 0
  File::Path: 0
  Plack::Middleware: 0
  Plack::Util: 0
  Plack::Util::Accessor: 0
  Storable: 0
  perl: 5.8.3
resources:
  license: http://dev.perl.org/licenses/
version: 0.12
